apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: citizen-portal

spec:

  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: razaessa/citizenportal-desc-backend:ad457aa4dfe7a41603eb6fa1e3fc72565ffc792b

        ports:
        - containerPort: 5000

        env:

        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET

        - name: MONGO_URI
          value: mongodb://mongodb:27017/citizenportal
