apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: citizen-portal

spec:

  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        image: razaessa/citizenportal-desc-frontend:c5403d59498a54e7739f277d10abc6560d608b4b

        ports:
        - containerPort: 80
